#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker tag docker-fedora29-ansible:latest doteast/docker-fedora29-ansible:latest
docker push doteast/docker-fedora29-ansible:latest

